### ISSUE TITLE
Mapping and preprocessing of low pass sequencing 

### ISSUE THREAD

**Issue by orr161** [odelaneau/GLIMPSE#101]
I would like to use “real" low pass (1X) WGS with GLIMPSE, and not down-sample. 

Are there any special considerations for sequence pre-processing, QC, mapping ?
I want to use the GATK best practices pipeline for[ WGS processing](https://gatk.broadinstitute.org/hc/en-us/articles/360035535912-Data-pre-processing-for-variant-discovery). 
This pipeline was developed for higher depth sequence data. 
Do you think it is appropriate to use for GLIMPSE?

**Comment by srubinacci** [comment]
Hi,
Yes, standard QC and mapping can be applied. 
The only difference is that, when using GATK, it is important to force-call genotype likelihoods at all variants of the reference panel rather than doing variant discovery. If this is not possible, consider using another caller, such as angsd or bcftools. If you have problems with this step, please let me know.

**Comment by orr161** [comment]
Thank you
