### ISSUE TITLE
Imputation using extracted BAMs 

### ISSUE THREAD

**Issue by sumudu-rangika** [odelaneau/GLIMPSE#110]
Hi Simone,

I have WGS 4x BAMs for ~2000 individuals. For my analysis I need only certain regions from each chromosome per-sample BAM. I have few things to clarify and appreciate your thoughts on these. 

1) Study samples are from an African ethnic group therefore, to generate the reference set I used the 1000 Genome phase3 VCF with extracted AFR samples, removed non-variant sites and sites missing in all samples and processed the sub-VCF as in the tutorial. 

2) The 2000 target BAMs I used, contain extracted regions of interest per chromosome. Therefore, the final VCF after genotypes likelihood calling against the reference VCF has many missing sites "GT . " . Since I'm interested in variants at extracted regions, before imputation I think I can safely remove these missing sites, in order to avoid imputation in regions that was absent in the input extracted BAM. 

3) My reference set (661 samples) is smaller than the study samples (2000 samples). To increase the accuracy of imputation can I use a VCF generated by an exome dataset with similar ethnicity (eg. UK Biobank ~200k exome data with African ancestry?). Most of my interested variants are in coding regions so I think I will not loose any important information by using exome data for imputation of my extarcted BAMs.

This is the first time I'm trying imputation and hope your answers will clear my doubts. Thanks a lot in advance.

Best
Rangi.

**Comment by srubinacci** [comment]
Hi Rangi, 
Sorry I was away for few days. Happy to help.
1. This is fine. A suggestion, if you use a reference panel of 661 samples on a relatively small set of sites, you might want to increase the parameter K of GLIMPSE_phase if possible. Also, as a suggestion, if your data is in b38 I think this version of 1000 Genomes has a pretty good phasing, as it was called and phased with TOPMed: 
ftp://share.sph.umich.edu/1000g-high-coverage/freeze9/phased/

2. Yes, I think it can be fine (e.g. for rare variants), but there might be caveats if you are not careful here. Maybe this might be unnecessary, you can probably simplify your pipeline by doing the filter after imputation.

3. Yes, in principle, however, it is a pretty unexplored idea and you might suffer from the missing data within coding regions (e.g. not sure the phasing methods work on WES data, and imputation as well). Indeed, in order to phase and impute from WES data, you might need to merge the available SNP array as well, as we did in this preprint (Figure 2d: https://www.biorxiv.org/content/10.1101/2022.10.19.512867v2.full.pdf). This might be a bit complex, also because you need to phase the WES+array data. In case send me an email and I can try to help you with that. But in general, I would try first to use the 1000 Genome project within 2 Mb regions of your target regions (and remember to add buffers!)

4. (not in your questons, but a suggestion) please impute all the 2000 samples together, GLIMPSE will jointly use and benefit from the ~2000 4x likelihoods!

Hope I helped, but in any case, feel free to drop me an email.

Best,
Simone

**Comment by sumudu-rangika** [comment]
Hi Simone,

Thanks a lot for the suggestions and helping me to clear my doubts !! 

- I have completed a preliminary run on imputing the interested regions. There were no issues so far in running the tool and worked great!! As you have suggested I will try with increasing the K parameter which I didn't do. 

- Initially, From the BAM file, I extracted 50kb upstream and downstream from the interested regions on chromosomes (please see the attached list of my regions). Therefore, I followed the steps as in the tutorial for chrX to generate chunks. I haven't included any window or buffers as in the chrX tutorial since the regions are small. Would this be okay or do I need to add buffers? 

Example command I ran:
$GLIMPSE_chunk --input ${refVCF} --region 2:29365639-234731946 --output $chunks/chunks.chr2.txt

- A good point is that I did use all the 2000 samples when imputing with 661 1000G reference samples !!

Thank you
Best,
Rangi

[itList.txt](https://github.com/odelaneau/GLIMPSE/files/9935712/itList.txt)
