### ISSUE TITLE
Concordance Gnomad file 

### ISSUE THREAD

**Issue by LouisLeNezet** [odelaneau/GLIMPSE#120]
Hi,

I would like to know how you generated the gnomad file used for the concordance analysis.
Is it the same as the one available here : [http://www.gnomad-sg.org/downloads](http://www.gnomad-sg.org/downloads)

If not, could you tell me the different step used to generate such a file ?

Thanks a lot !

**Comment by matosmr** [comment]
Hi, I am also confused about this step. I do not understand how to come up with the validation data set and the reference sites for the concordance steps. If I am trying to impute, it is because I do not have the true genotypes. Is the concordance against the same reference from which I performed the imputation?

Thanks a lot!

**Comment by srubinacci** [comment]
Hi,

Happy to clarify this. The gnomad file is just a file with allele frequencies (either INFO/AC and INFO/AN or INFO/AF) and no genoype data. This is obtained gnomad V3 (in the link you posted, gnomad v3 tab) for the desired chromosome. As these files are very large as they contain information of many human populations, I restricted the file to the populations of interest (I think EUR and AFR) using bcftools annotate -x command. 

Maybe a bit of context about gnomad. Gnomad is a large high-coverage WGS dataset containing data of thousands of human samples from different populations. Genotype data is not available, but they made available allele frequencies for many human populations. Here I want to identify common and rare variants to compute the r2 statistics in allele frequency bins. So I used the gnomad v3 dataset. I could have used the reference panel allele frequencies as well if the populations were matching.

@matosmr Indeed, it can be confusing at the begging. Hope the following can help to improve your understanding, 
What we do in the tutorial (and in many imputation papers) is to simulate low-coverage WGS data from high-coverage WGS to see how good imputation is. As the original file is high-coverage, we have genotype calls, and we consider them the gold standard (="validation"). Then we take the high-coverage BAM, we downsample the reads to the desired coverage (e.g. 1x), and we perform imputation from a reference panel. Finally, we compared our imputed calls with the validation calls. The standard way to do that is using the r2 statistic, where we take variants at different minor-allele frequency bins and we compute a single r2 per bin. This is because we know imputation is very good at common variants and less good at rare variants. Therefore we need some definition of what is common and what is rare for the population of interest, and in this case we use the Gnomad dataset, as I explained above to Louis. This is why we require a region, the frequency file, the validation file and the imputed file as input of the concordance step.

Now, going back to your point: indeed usually you do not have high-coverage data, but only low-coverage. Then, in this case, you are not able to run the concordance test and test directly how good your imputation is. For this reason, in the field of association studies, people have been using information scores to carrying out quality control of imputed genotype data (e.g. GLIMPSE report the INFO score, taken by the IMPUTE software). Also, we know that common variants are well-imputed and rare variants aren't, therefore you can also filter rare variants. I recommend this great review about imputation by Jonathan Marchini and Bryan Howie: https://doi.org/10.1038/nrg2796 for more information.

Hope this helps,

Simone

**Comment by matosmr** [comment]
Hi Simone, Thank you for taking your time to clarify this. I will definitely check out those resources! Have a great day!
