### ISSUE TITLE
Unexpected output

### ISSUE THREAD

**Issue by jieteliang** [odelaneau/GLIMPSE#131]
GLIMPSE_phase --input part1_50k.recode.vcf.gz --reference partque1_4.vcf.gz --output imputation_part1_29.vcf.gz --input-region 29:27573-51093670  --output-region 29:27573-51093670 --ne 150 --log imputation_part1_29.log

Above is my command.
My input file is 50k SNP.My output file is still 50K SNP.
Both my input and reference files are whole genomes.
I don't know where the problem is.
hope you help me poor man.

**Comment by jieteliang** [comment]
Thank you for the reply.

Yes, as you said I want to fill in the missing variants of small groups.

**Comment by srubinacci** [comment]
Hi,

if you don't have genotype likelihoods but only hard called genotypes, you might want to use standard SNP-array imputation software for example [IMPUTE5](https://www.dropbox.com/sh/mwnceyhir8yze2j/AADbzP6QuAFPrj0Z9_I1RSmla?dl=0) instead of GLIMPSE. Remember to phase your 50k SNPs first, using [SHAPEIT4](https://github.com/odelaneau/shapeit4/releases)

Hope this helps,

Simone

**Comment by jieteliang** [comment]
Thank you for your response.

Microarray simulated from 50k SNPs randomly extracted from the whole genome（vcf）.

Use this chip for 5-fold cross-validation

**Comment by srubinacci** [comment]
Ok so yes, I think it's more proper to use standard SNP array prephasing + imputation (e.g. SHAPEIT4 for the prephasing  and IMPUTE5 for the imputation).

GLIMPSE is for low-coverage WGS datasets.

Hope this helps
Simone

**Comment by jieteliang** [comment]
OK, thank you very much for your patience.

Wish you happy every day！
