### ISSUE TITLE
Bioconda and impute 5

### ISSUE THREAD

**Issue by LouisLeNezet** [odelaneau/GLIMPSE#137]
Hi,
I just finished integrating Glimpse 1 and 2 and shapeit5 to nf-core !
It works really great.
I'm trying now for impute5.
Unfortunately there isn't a stable repository as glimpse.
Would it be possible to host it on your Github account to be able to use it with Conda ?
Thanks a lot,
Louis

**Comment by srubinacci** [comment]
Hi,

Glad to hear that your workflow runs correctly.

Indeed, I implemented impute5 during my Phd when I was part of another lab, and it is subject to a different licence (closed-source but free to use for academic institution). Due to this, we unfortunately cannot host it on github and cannot be compiled by users.

**Comment by LouisLeNezet** [comment]
Would it still be possible to host the static to a Github Account ?
It would allow the use of it with conda even without the need to compile it 😄 
A bit as how I test here https://github.com/bioconda/bioconda-recipes/pull/39843

**Comment by srubinacci** [comment]
A new version of Impute5 will be soon available. Will try to host the static binary it on github so that later it can be used for conda as you suggested. I will update here with the location when available.
