### ISSUE TITLE
clarification on imputation

### ISSUE THREAD

**Issue by sahwa** [odelaneau/GLIMPSE#15]
I've been using GLIMPSE on imputing low coverage ancient DNA data and needed a bit of clarification. 

From my initial at the results, it seems like positions in the genome which are present in both the reference bcf and the chunks file, but that are not present in any of the samples in the target input bcf (i.e., completely missing, not just flat likelihood) are not present at all in the output imputed bcf. This is the case as the genotype likelihood caller I am using (ATLAS) doesn't emit positions where no reads are present (as opposed to bcftools).  

This possibly seems at odds with the paper (page 17, line 41), which says that 'In the case of completely missing data, a flat likelihood is called by GLIMPSE, allowing the method to perform  standard imputation.

So, are positions which are totally missing from all samples the input bcf, but present in the reference and the chunks file supposed to be imputed and present in the output bcf? Thank you.

**Comment by SimoneRubinacci** [comment]
Hi,

At the moment GLIMPSE really works on the intersection of the positions. Therefore, in your case you might want to add the missing positions containing missing data (as ".") and GLIMPSE will perform standard imputation as written in the paper, calling flat likelihoods in the position. 
However, in the next release (v1.1) that will be out in few days, between other improvements there will be an option called "_--impute-reference-variants_" to perform imputation at variants only present in the reference panel. 
However this won't be the default option, because people might get confused and we strongly recommend the call the likelihoods at each variable position of the reference panel, even if the resulting dataset will contain missing data. 

Hope I answered to your question,

Best wishes,
Simone

**Comment by sahwa** [comment]
ok thanks. is there a mailing list which lets us know when the new versions have been released?

best, Sam.

**Comment by SimoneRubinacci** [comment]
Hi Sam,

No need of specific mailing lists. You can watch the project and github will notify you about new releases. 

Best wishes,
Simone
