### ISSUE TITLE
Missing genotypes in reference panel

### ISSUE THREAD

**Issue by lordkev** [odelaneau/GLIMPSE#16]
Thanks for the wonderful tool!

Could you explain how missing genotypes in the reference panel are handled? For example, if some sites have up to 1%, 5%, 10% or more samples missing genotypes?

Do you have any suggestions on whether it would be better to err on the side of having more accurate genotypes in the reference panel, or less accurate but more complete?

Essentially, I am trying to create a custom reference panel using data from microarray genotyped samples imputed against a very large reference panel. Happy to hear any insight or suggestions you may have.

**Comment by SimoneRubinacci** [comment]
Hi,

Thanks for your question. In this version of the software we do not handle missing genotypes in the reference panel. Therefore unfortunately you might need to discard those variants or if you decide to impute them first, try to be very careful, since it might be dangerous.

Introducing non-accurate and badly phased genotypes in the reference panel can really harm the performance of imputation even at variants where the genotypes are accurate and well-phased. Using a reference panel from imputed SNP array data is a bit worrying in my opinion. I would at least test the performance of this against 1000GP as a reference panel, for example.

Hope this helps,

Simone

**Comment by lordkev** [comment]
Yes, thank you for the feedback. I was trying to expand my reference panel, especially when it comes to particular populations, but it sounds like I may need to rethink my approach.
