### ISSUE TITLE
discordance in GLIMPSEv1 output genotypes between the two genotyping approaches

### ISSUE THREAD

**Issue by CjeicaM** [odelaneau/GLIMPSE#195]
Hi,
Maybe not an issue but a question. I am trying to integrate GLIMPSEv1 into our pipeline and I was comparing two tools to obtain the genotypes and genotype likelihoods, and I noticed some discordance between the two genotyping approaches (NRD=3.01) even between the non-downsampled high-coverage control, and I was wondering what might be the cause.
Below one such SNP
the format and sample fields for the GLIMPSEv1 input:
genotyping method 1    GT:DP:AD:GQ:PL 1/1:6:0,6:18:263,18,0
genotyping method 2    GT:PL:DP 1/1:185,18,0:6

and info, format and sample fields from the output:
genotyping method 1     RAF=0.501398;AF=0.654;  INFO=0.718;AC=1;AN=2    GT:DS:GP:HS     0/1:1.251:0,0.749,0.251:629423
genotyping method 2     RAF=0.501398;AF=0.62775;INFO=0.634;AC=2;AN=2    GT:DS:GP:HS     1/1:1.658:0,0.342,0.658:720886

Everything was run using the same parameters on chromosome 20 from 1000 genome data. With the exception of this SNP there were no differences in genotypes in the 10kbp window around the SNP both in input or output.

**Comment by srubinacci** [comment]
Hi,

I can just give maybe obvious commentary here.
Both methods produce fairly similar genotype likelihoods, but after imputation, the outputs fairly different probabilities. This is a variant that should be fairly well imputed (due to the AF in the ref panel), but this difference might be due to phasing uncertainty. This seems not to be a difference between genotyping methods, but more like a stochastic error. Maybe you can look at the dosages, or rerun impuation with a seeds to try to average out this type of errors.

**Comment by srubinacci** [comment]
Hi,

I can just give maybe obvious commentary here.
Both genotyping methods produce similar genotype likelihoods, but after imputation, the outputs fairly different probabilities. This is a variant that should be well imputed (due to the AF in the ref panel), but as every probabilistic method, a difference might be due to phasing uncertainty. This seems not due to different genotyping methods, but more like to the stochasticity of the phasing. Maybe you can look at the dosages, or rerun imputation with a seeds to try to average out this type of errors.

Hope this helps,

Simone
