### ISSUE TITLE
[31mERROR: [0mERROR base sequences.

### ISSUE THREAD

**Issue by Xinyi2796** [odelaneau/GLIMPSE#198]
Hi,
I am using your GLIMPSE2_phase_static and encountered some problems. I used the bovine genome ARS-UCD1.2 as the reference genome to impute my 636 low-depth sequenced samples.  The attachment contains the error message I received. My BAM files did not trigger the same error when using other imputation software like QUILT, and were successfully imputed with that software
Below are my shell script and error message:
#!/bin/bash

REF=/compute/zhangxy/fq/GLIMPSE/Chr2
BAM=bam.txt
while IFS="" read -r LINE || [ -n "$LINE" ]; 
do   
printf -v ID "%02d" $(echo $LINE | cut -d" " -f1)
IRG=$(echo $LINE | cut -d" " -f3)
ORG=$(echo $LINE | cut -d" " -f4)
CHR=$(echo ${LINE} | cut -d" " -f2)
REGS=$(echo ${IRG} | cut -d":" -f 2 | cut -d"-" -f1)
REGE=$(echo ${IRG} | cut -d":" -f 2 | cut -d"-" -f2)
OUT=/compute/zhangxy/fq/GLIMPSE/Chr2/Chr2.imputed
/compute/zhangxy/fq/software/glimpse/bin/GLIMPSE2_phase_static --bam-list ${BAM} --reference ${REF}_${CHR}_${REGS}_${REGE}.bin --threads 8 --output /compute/zhangxy/fq/GLIMPSE/Chr2/${OUT}_${CHR}_${REGS}_${REGE}.bcf
done < /compute/zhangxy/fq/GLIMPSE/chunks.chr2.txt
Could you please help me to identify the cause of the problem and provide a solution? Thank you very much.
[slurm-156520.txt](https://github.com/odelaneau/GLIMPSE/files/14329109/slurm-156520.txt)

**Comment by srubinacci** [comment]
Hi,

It's an error when parsing the BAM/CRAM files.
Can you pre-compute genotype likelihoods using bcftools (or GATK, or any other similar software) and run GLIMPSE with the "--input-gl" option instead of the "bam-list" option?
To create genotype likelihoods at a set of reference panel sites you can use the instructions from the GLIMPSE1 website:
https://odelaneau.github.io/GLIMPSE/glimpse1/tutorial_b38.html#run_likelihoods

Hope this helps,

Simone
