### ISSUE TITLE
Getting smaller chunk size

### ISSUE THREAD

**Issue by ssinh10** [odelaneau/GLIMPSE#202]
Hi @srubinacci,

I want to optimize for time as I need to work on hundreds of bam files and for that I want to impute very specific regions, I am doing following steps:

1. Download 1000 genome reference panels and process it based on tutorial of GLIMPSE2
2. Running GLIMPSE2_chunk_static on the reference panel and map file here is my command 
``GLIMPSE2_chunk_static --input ../reference_panel/1000GP.chr17.sites.vcf.gz --region 17:1732952-1832952 --sequential  --output chunks.chr17_sample_seq.txt  --window-mb 3 --map ../maps/genetic_maps.b37/chr17.b37.gmap.gz``

When I run this I do not get any chunks as output. I tried it with different windows size.  The message says

> Splitting data long into chunks and writing to [chunks.chr17_sample_seq.txt]
 

>  * Region appears to small to find a sequential solution (only one chunk detected). Check your parameters if this is not a desired behavior.

>   * Terminal window [0] -buffer:[17:1732977-1832832] / +buffer:[17:1732977-1832832] / L=0.399311cM / L=99855bp / C=3237

 

>  * #chunks = 1

However when I use recursive I get at least one chunk as output. 

My question is
1. Is there an optimized way to create reference bins for small targeted part and then impute that particular region in the low coverage bam. 
2. Why is --sequential preferred over --recursive. What are pros and cons. 

Thank you for any insights you can provide, links or tutorials, that would help me optimize my work flow. 

Thanks

**Comment by srubinacci** [comment]
Hi,

For this specific problem you might not need to use the chunk program as this could be likely done manually. Would 1732977-1832832 + a (e.g 250kb) buffer work for you?

Keep in mind the program was developed to chunk an entire chromosome and this seems like a specific edge case where we have only one small region. I am not sure why you what to create smaller chunks - as you already work on a small chunk.
I bet the program is confused that the region in input is small and does not produce a valuable input.

The difference between --sequential and --recursive is in the name: in the first case it goes sequentially in the region of interest, generating minimal chunks respecting your filtering option; the problem is at the last chunk that can be too small when we chunk in this way. For this reason, if it detects this case, it will try slightly different parameters and try again until (hopefully) it finds a good solution.
The recursive option is even simpler, it runs recursively by setting the whole region as a chunk. If this can be sliced (e.g. current region is not minimal), it will recursively split it in two. A problem with this approach is the divide-et-impera approach, dividing a  region into two, therefore potentially returning regions up to 2x larger than the parameters given.

Hope this helps,

simone

**Comment by ssinh10** [comment]
Hi @srubinacci Thank you for the explanation. A 250 kb buffer works. I was basically trying to see if I can reduce the time complexity further by making the selected region smaller. But I ended up running it on 100 samples on all the chromosome and then look at these specific regions and it worked pretty well, just took a bit longer which is expected. 

I am still working on this but for now it seems to work with entire chromosome. 

Thanks again.
