### ISSUE TITLE
Differences between 1.0.1 and 1.1.0

### ISSUE THREAD

**Issue by lmtani** [odelaneau/GLIMPSE#26]
I'm studying if it is possible to impute my exome data and notice that GLIMPSE has changed the way the imputed sites are reported.

It seems like only positions above an INFO cutoff are being written in the final VCF file. Is it the intended behavior?

I'm working using a very small single exome subset, here are some of the input details:
- Region: chr20:1-2000000 (GRCh38)
- Reference Panel (1kgp): 58739 sites, 56608 after quality step.
- Sites covered by WES: 6696, 252 variants.

The static bin of version 1.1.0 output 6733 sites, and 293 of these are variants.
The static bin of version 1.0.1 output 56608 sites, and 2773 of these are variants.

This is the command used:

```bash
GLIMPSE_phase_static \
    --input <wes.from.bcftools.sites.vcf.gz> \
    --reference <panel.reference.vcf.gz> \
    --map <chr20.b38.gmap.gz> \
    --input-region <chr20:79702-1999956> \
    --output-region <chr20:79702-1999956> \
    --output <chunk.00.bcf>
```

Also, thank you for the detailed tutorials.

**Comment by srubinacci** [comment]
Hello,

Indeed there's a difference in the management of the input between v1.1.0 and v1.0.1, but it should be relatively minor, and you shoudn't be affected. Both the versions should impute only the set of variants common between the reference panel and the target samples. Meaning that if a variant is present only in the reference panel, this is automatically discarded. 

However, GLIMPSE (both versions) calls a flat likelihood for each target sample if the site is present in the reference panel and also present with no data in the target genotype likelihood (GL) dataset, assuming that the GL caller did not find informative information in the reads.
To this regard, we introduced an option "--impute-reference-only-variants" in v1.1.0 (https://odelaneau.github.io/GLIMPSE/commands.html#phase) where we allow imputation at variants only present in the reference panel. This is meant to impute sporadicly missing data. In this way, GLIMPSE is able to call a flat likelihood at each position of the reference panel even if the target GL dataset does not contain all these sites. However, I should note that this option is relatively dangerous for the general use, as it would be much better it is the GL caller itself to throw a flat likelihood rather than GLIMPSE, as GLIMPSE does not check the reads.
Hope now is more clear what we do and why we introduced this option. 

Regarding the results you get, I would check the content of the `wes.from.bcftools.sites.vcf.gz` file and see what kind of information it does have at positions not covered by WES: does it already contain a flat likelihood or the sites are not in the file at all?

Regarding your observation about the possible INFO cutoff, this is not the intended behaviour, but I guess a conseguence of using only highly accurate (covered by wes) sites. 

Hope this helps.

Best wishes,
Simone

**Comment by lmtani** [comment]
Hi,

I think maybe it would be useful if I make available my input dataset (very small to run fast), prepared following your tutorial steps. It is on Google Drive.

- [chr20.b38.gmap.gz](https://drive.google.com/file/d/1WyRVc2frXh9rH43hXvvHJTdBapqEDffY/view?usp=sharing)
- [qc_refecence.vcf.gz](https://drive.google.com/file/d/1fv_BhM7U16Nl_tlHR2NAWlMhj_FXbyqO/view?usp=sharing)
- [qc_refecence.vcf.gz.tbi](https://drive.google.com/file/d/1V4Rc7XsNCQcVfgEm6eU9qcYzhpg39jNq/view?usp=sharing)
- [wes.from.bcftools.sites.vcf.gz](https://drive.google.com/file/d/1oh9xMFgpM3uGNP6mOvIZnztkSMJ95B_4/view?usp=sharing)
- [wes.from.bcftools.sites.vcf.gz.tbi](https://drive.google.com/file/d/192GyNFg_pz-n7bQdYSsXwE-I5kPwXg-c/view?usp=sharing)

And the command:

```bash
GLIMPSE_phase --input wes.from.bcftools.sites.vcf.gz \
              --reference qc_reference.vcf.gz \
              --map chr20.b38.gmap.gz \
              --input-region chr20:79702-1999956 \
              --output-region chr20:79702-1999956 \
              --output mini-region.vcf.gz
```

I've tried it with the `--impute-reference-only-variants` parameter, but have similar results. Here is the stdout info from the two versions:

Version 1.0.1
```
[GLIMPSE] Phase and impute low coverage sequencing data
  * Author        : Simone RUBINACCI & Olivier DELANEAU, University of Lausanne
  * Contact       : simone.rubinacci@unil.ch & olivier.delaneau@unil.ch
  * Version       : 1.0.1
  * Run date      : 14/12/2020 - 11:29:10

Files:
  * Input VCF     : [wes.from.bcftools.sites.vcf.gz]
  * Reference VCF : [qc_reference.vcf.gz]
  * Genetic Map   : [chr20.b38.gmap.gz]
  * Output VCF    : [mini-region.vcf.gz]
  * Input region  : [chr20:79702-1999956]
  * Output region : [chr20:79702-1999956]

Parameters:
  * Seed       : 15052011
  * #Threads   : 1
  * #Burnin    : 10
  * #Main      : 10
  * PBWT depth : 2
  * PBWT modulo: 8
  * Init K     : 1000

Initialization:

Parsing specified genomic regions
  * Input region  [chr20:79702-1999956]
  * Output region  [chr20:79702-1999956]
  * VCF/BCF scanning [Nm=1 / Nr=2504 / L=56608 / Reg=chr20:79702-1999956] (5.85s)
  * VCF/BCF parsing done (8.12s)
  * GMAP parsing [n=2903] (0.00s)
  * cM interpolation [s=2835 / i=53773] (0.07s)
  * Region spans 1920255 bp and 7.00 cM
```

Version 1.1.0

```
[GLIMPSE] Phase and impute low coverage sequencing data
  * Author        : Simone RUBINACCI & Olivier DELANEAU, University of Lausanne
  * Contact       : simone.rubinacci@unil.ch & olivier.delaneau@unil.ch
  * Version       : 1.1.0
  * Run date      : 14/12/2020 - 11:56:17

Files:
  * Input VCF     : [wes.from.bcftools.sites.vcf.gz]
  * Reference VCF : [qc_reference.vcf.gz]
  * Genetic Map   : [chr20.b38.gmap.gz]
  * Output VCF    : [mini-region.vcf.gz]
  * Input region  : [chr20:79702-1999956]
  * Output region : [chr20:79702-1999956]

Parameters:
  * Seed       : 15052011
  * #Threads   : 1
  * #Burnin    : 10
  * #Main      : 10
  * PBWT depth : 2
  * PBWT modulo: 8
  * HMM     : Recombination rates given by genetic map
  * Ploidy     : All samples are diploids in this region
  * Init K     : 1000

Initialization:

Parsing specified genomic regions
  * Input region  [chr20:79702-1999956]
  * Output region  [chr20:79702-1999956]
  * #samples = 1 [0 haploids/ 1 diploid]
  * VCF/BCF scanning [Reg=chr20:79702-1999956 / L=56608 (Lgl= 56608 (100%) - Lnl= 0 (0%))] (5.97s)
  * VCF/BCF scanning [Nm=1 (Nmh=0 - Nmd=1) / Nr=2504 (Nrh=0 - Nrd=2504)]
  * VCF/BCF parsing done (7.92s)
  * GMAP parsing [n=2903] (0.00s)
  * cM interpolation [s=326 / i=6407] (0.00s)
  * Region spans 1902099 bp and 6.96 cM
```

The main difference is on `cM interpolation` values, but I don't know yet what "s" and "i" means.

---

Before preparing the subset for debug purposes I was assessing the GLIMPSE results, following the [F1-score](https://en.wikipedia.org/wiki/F-score) of imputed variants on regions more distant from the WES data, i.e: False Positives and False Negatives variants inside exome targets, than same metrics for variants at least 100bp, 1kb,... from previous interval boundaries (starting from exons). Here are some results:

![image](https://user-images.githubusercontent.com/12699242/102084868-92d9e480-3df4-11eb-8e82-cfde09699663.png)

Y=F1 score, X=MAF on reference panel.

**Comment by lmtani** [comment]
@srubinacci Now I see what happened: in the file `wes.from.bcftools.sites.vcf.gz` there were sites without ngs reads and because of this I think` --impute-reference-only-variants` was not working as expected.

Now I added a step where I keep only sites with coverage (`bcftools view -i 'INFO/DP >= ~{min_dp}'`) and it is working.

I think we could close this issue.

Thank you!
