### ISSUE TITLE
index the TSV file

### ISSUE THREAD

**Issue by alek0991** [odelaneau/GLIMPSE#3]
Hello,
I get the following error when I try to run step3_script_GL.sh:
`[E::_regions_match_alleles] Compressed and indexed targets file is required`

I added `tabix -s1 -b2 -e2 reference_panel/1000GP.chr22.noNA12878.sites.tsv.gz` after the following line to fix this and it works for me. Am I missing something?

https://github.com/odelaneau/GLIMPSE/blob/ce7b9f7e92a0166a18c9f5868c405e445523547a/test/step3_script_GL.sh#L7

Thanks,
Ali

**Comment by SimoneRubinacci** [comment]
Hi Ali,

Thank you for this. I've just re-run step1-3 and I don't encounter the same error, it seems that an indexed tsv file is not required. Not sure why, my guess is that we use different program versions.
Anyway your suggestion makes perfectly sense since bcftools often works with indexed files. So I've just pushed a new version of step3 with your suggestion.
