### ISSUE TITLE
Running GLIMPSE_concordance

### ISSUE THREAD

**Issue by malmarri** [odelaneau/GLIMPSE#35]
Hi,

Thanks for the great tool.

For the GLIMPSE_concordance test, in the documentation you show the command:

```
 ./bin/GLIMPSE_concordance --input concordance.lst --minDP 8 --output GLIMPSE_concordance/output --minPROB 0.9999 --bins 0.00000 0.00100 0.00200 0.00500 0.01000 0.05000 0.10000 0.20000 0.50000ex \
--info_af AF_nfe --thread 4
```
I just wanted to confirm that allele info tag supplied in the command "AF_nfe". Should you be using minor allele frequency (MAF_nfe) instead of allele frequency (AF_nfe)? 

Thanks.

**Comment by srubinacci** [comment]
Hi,

Indeed, we use MAF in the concordance program, but we take the AF field as it is usually more common in VCF files. The simple AF to MAF conversion is performed internally in the program:

https://github.com/odelaneau/GLIMPSE/blob/38ebc50f0d2e924f2477170773247281fca77dcf/concordance/src/containers/call_set_reading.cpp#L269

Hope this helps,
Simone

**Comment by malmarri** [comment]
Thanks for the quick reply and explanation.

I have tried the command using either 'AF' and 'MAF' and find different results, from the rsquare.grp.txt.gz file:

`bin/GLIMPSE_concordance --input concordance.$i.lst --minDP 8 --output validation.$i.EUR.AF --minPROB 0.9999 --bins 0.001 0.005 0.01 0.050 0.50 --af-tag AF_EUROPE --thread 8;done`
```
0 9706 0.00257017 0.389679 0.151849
1 5820 0.00695717 0.68705 0.472038
2 7143 0.0232473 0.726916 0.528407
3 20693 0.257076 0.823679 0.678447
```
`bin/GLIMPSE_concordance --input concordance.$i.lst --minDP 8 --output validation.$i.EUR.MAF --minPROB 0.9999 --bins 0.001 0.005 0.01 0.050 0.50 --af-tag MAF_EUROPE --thread 8;done`
```
0 9706 0.00257017 0.786895 0.619204
1 5820 0.00695717 0.835565 0.698168
2 7143 0.0232473 0.835428 0.69794
3 20693 0.257076 0.846766 0.717013
```
I'm wondering if you have any idea why the values are different? I used `bcftools +fill-tags` to add the AF and MAF annotations. In addition, what is the difference between the 4th and 5th column in the rsquare.grp.txt.gz file? I understand that the second column is the number of SNPs and the third is the allele frequency bin, not sure which of the 4th and 5th are the r2 imputed vs validation genotypes.

Thanks again.

**Comment by srubinacci** [comment]
Hi, 

Indeed my latest sentence could have generated some confusion as it was not completely clear (although I was just trying to make things easier). What I meant by "using MAF_nfe should be equivalent" is just at the binning level (same marker goes to the same MAF bin). However, **the program is not meant to run with the INFO/MAF option**, but with the alternative allele frequency INFO/AF.

The reason is because computing the r^2 for MAF also involves "flipping" the alleles REF/ALT to MAJ/MIN for all the datasets. This is performed internally in the program using the usual --info_af AF, as it directly keeps track of the flipped alleles.

To run the validation program directly using the INFO/MAF option you would need to manually switch all your datasets from REF/ALT to MAJ/MIN.

Going back to your example, the program puts the same markers to the same same bins, however the dosages/genotypes in the second example are wrong, as the program treats them as MAJ/MIN (as there are no switches) while they are actually REF/ALT and would need to be switched in some case.

The fourth column is just r, while the fifth is r^2. You can completely ignore it.

Will edit slightly my previous reply to make it clear (in case somebody else will just read my first reply.
Hope this is more clear now,

Simone

**Comment by malmarri** [comment]
Thank you very much for the clear explanation.
