### ISSUE TITLE
Number of threads to use

### ISSUE THREAD

**Issue by alek0991** [odelaneau/GLIMPSE#4]
Hello,
I have been playing with the number of threads, `--thread`,  in the following line but I don't see any significant improvement in computational costs. 
https://github.com/odelaneau/GLIMPSE/blob/ef76d1a4ae77cd5c455f4e7f8568e735673b11e0/test/step5_script_impute.sh#L15

In fact, it gets even worse in the following examples.  Is this what you would expect or I am doing something wrong? 

I am using Linux with 8 cores and 50G of memory. This is output of `/use/bin/time -v 5_script_impute.sh` with `--thread 8`:

```
        Command being timed: "./step5_script_impute.sh"
        User time (seconds): 822.48
        System time (seconds): 4.14
        Percent of CPU this job got: 100%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 13:46.46
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 921916
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 2836097
        Voluntary context switches: 6418
        Involuntary context switches: 9533
        Swaps: 0
        File system inputs: 0
        File system outputs: 28496
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

And this is with `--thread 1`:

```
        Command being timed: "./step5_script_impute_thread1.sh"
        User time (seconds): 708.06
        System time (seconds): 2.27
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 11:50.68
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 888652
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 764037
        Voluntary context switches: 2156
        Involuntary context switches: 8477
        Swaps: 0
        File system inputs: 0
        File system outputs: 28488
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

**Comment by SimoneRubinacci** [comment]
Hi,
Yes, this makes sense. Glimpse implements a double parallelization scheme: first, by chunk since every chunk can be a completely parallel job; second, by multi-threading, (of the most costly parts of the algorithm) by assigning at each thread a subset of target individuals.

In the test example, you are running GLIMPSE on one single target individual, therefore you don't gain any improvement from the multi-threaded strategy. In a more realistic scenario, with hundreds or thousands of target individuals, you will see a great benefit in terms of time.

My recommendation is to parallelize by chunk first, since the speedup obtained should be a approximately a multiple of the number of jobs running in parallel. Then each job can also be multi-threaded in the case the number of cpus available is high (for example on a modern cluster).

**Comment by alek0991** [comment]
Thank you so much. This is very helpful.
