### ISSUE TITLE
Running GLIMPSE_concordance

### ISSUE THREAD

**Issue by batelz** [odelaneau/GLIMPSE#42]
Hi,

When running the code as instructed in 8.1
```
 > ./bin/GLIMPSE_concordance --input concordance.lst --minDP 8 --output GLIMPSE_concordance/output --minPROB 0.9999 \
 > --bins 0.00000 0.00100 0.00200 0.00500 0.01000 0.05000 0.10000 0.20000 0.50000ex \
 > --info_af AF_nfe --thread 4
```
, I get two errors. 
The first:

> Error parsing command line arguments: unrecognised option '--info_af'

When I remove the option altogether, I get:

> Error parsing command line arguments: the argument ('0.50000ex') for option '--bins' is invalid

I assume I need to delete the "ex"...

Can you explain what is the --info_af option and if I should lose the "ex" in the bins?

Thanks

**Comment by srubinacci** [comment]
Hi, 
Indeed, the "ex" is just a typo and if you look at `step8_script_concordance.sh`, you'll notice there's no "ex".
Thanks, will definitively correct this soon.

The --info_af option is meant to define the allele frequencies of the population of interest, in this case non-Finnish Europeans, taking from the INFO/AF_nfe field of the allele frequency file you defined in the list, in this case [Gnomad v3](https://gnomad.broadinstitute.org/blog/2019-10-gnomad-v3-0/). 

You need to specify the allele frequency field, as otherwise the default would be to take INFO/AF, absent from the file we provide, e.g.:
`bcftools view -H gnomad.genomes.r3.0.sites.chr22.isec.bcf | head -n 1
chr22	16367322	rs542895279	C	T	394	AC0	AF_afr=0;AF_nfe=0`

**Comment by batelz** [comment]
Hi @srubinacci,
The problem still consists.
Whenever I run the command or the .`/step8_script_concordance.sh` script, I get the following message:
`Error parsing command line arguments: unrecognised option '--info_af'`

I first faced this issue when working according to the tutorial.
Now again - when working on another simulation.

Why can't the script acknowledges the option?
