### ISSUE TITLE
GLIMPSE Tutorial, undefined reference to `boost::program_options`

### ISSUE THREAD

**Issue by ssadhuka** [odelaneau/GLIMPSE#47]
Hi,

I am running the GLIMPSE tutorial to get the software up and running and am getting the following error (repeated in many places):

`obj/chunker_parameters.o: In function `chunker::declare_options()':
chunker_parameters.cpp:(.text+0x4d7): undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'`

Reading up online (e.g. [here](https://stackoverflow.com/questions/39591067/undefined-reference-to-boostprogram-options-in-xubuntu)), it appears that there's an issue with libboost_program_options.  I'm running boost on a cluster and thus have edited the makefiles for each project (chunk, phase, etc.) as follows:

```console
#CONDITIONAL PATH DEFINITON
desktop: HTSSRC=/broad/cholab/shuvom
desktop: HTSLIB_INC=$(HTSSRC)/htslib
desktop: HTSLIB_LIB=$(HTSSRC)/htslib/libhts.a
desktop: BOOST_INC=/broad/cholab/shuvom/boost_1_76_0/include
desktop: BOOST_LIB_IO=/broad/cholab/shuvom/boost_1_76_0/lib/libboost_iostreams.a
desktop: BOOST_LIB_PO=/broad/cholab/shuvom/boost_1_76_0/lib/libboost_program_options.a
desktop: $(BFILE)
```

I am using GCC-5.2 as my compiler.  I'm not sure what the issue is here, since BOOST_LIB_PO does point to a valid file.  Any ideas?

**Comment by ssadhuka** [comment]
UPDATE: I downgraded my boost version to 1.73.0 (as recommended on the installation guide) and it worked.

**Comment by karinkumar** [comment]
Hello I am having the same issue, but with _GLIMPSE 2._ My error is  `undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'`

I checked my boost version and it is 1.65.1 so not sure what the problem because I do not need to downgrade as @ssadhuka did. The documentation says boost must be 1.65 or greater.

I am compiling the code and have edited the DESKTOP section of the makefiles accordingly: 
```
desktop: HTSSRC=~
desktop: HTSLIB_INC=$(HTSSRC)/htslib
desktop: HTSLIB_LIB=$(HTSSRC)/htslibs/libhts.a
desktop: BOOST_INC=/usr/include
desktop: BOOST_LIB_IO=/usr/lib/x86_64-linux-gnu/libboost_iostreams.a
desktop: BOOST_LIB_PO=/usr/lib/x86_64-linux-gnu/libboost_program_options.a
desktop: BOOST_LIB_SE=/usr/lib/x86_64-linux-gnu/libboost_serialization.a
desktop: $(BFILE)
```
