### ISSUE TITLE
finding boost library file 

### ISSUE THREAD

**Issue by erikenbody** [odelaneau/GLIMPSE#5]
Hi there,

I'm keen to test this software out. However, I am having trouble on our linux cluster setting up the dependencies. Boost is installed on the machine so e.g. `/usr/include/boost/iostreams/` exists. However, the library files e.g. `libboost_iostreams.a` do not, which is required as noted on the [install](https://odelaneau.github.io/GLIMPSE/installation.html) help page I followed.

When I went to compile from boost.org I found that these library files are not contained in the typical install of boost. The development version seems only accessible via sudo apt-get. Do you have any suggestions to get this running on a cluster without root access? I also failed to install on my macbook (in that homebrew does not have the development version of boost), so I expect that I am missing something very obvious here. 

Thank you for any help!

Erik

**Comment by SimoneRubinacci** [comment]
Hi Erik,

Thank you for your message. 
I am not sure why you did not find the required libraries in your installation of boost, since they are pretty standard and present in the default installations of boost. 

I suggest you three options, hope at least one of the will work:
1. First, you I'd download and install your own version of boost in a local directory again. It should pretty straightforward and root access is not required. I recommend to follow these [instructions](https://www.boost.org/doc/libs/1_73_0/more/getting_started/unix-variants.html#easy-build-and-install) (e.g. for version 1.73), in particular the `./bootstrap.sh --prefix=path/to/installation/prefix` is the key command. After installation `./b2 install`, you'll have an _include_ and _lib_ folder; in the _lib_ folder there should be a static library named `libboost_iostreams.a`. The include folder must then be used for the `BOOST_INC` variable in our `makefile`.
I have very recently did this on a cluster and it worked.
2. If boost is installed in your system, you should have at least a shared object version of `libboost_iostreams`, called  `libboost_iostreams.so`. You can try to link against it instead of `libboost_iostreams.a`.
3. (as a last option!) We provide already compiled static binaries in the `static_bins` folder. I will always recommend to compile your own version, since you might get a significant performance improvement. However, if your purpose is just to try the software, these binaries should be easy to use.

Hope that's helpful and please let me know if I can further help you.
Best,

Simone

**Comment by erikenbody** [comment]
Hey Simone,

Thank you for taking the time to help me troubleshoot! I had not done my own install of boost correctly and following the install instructions more faithfully (no surprise there!) provided me with the correct library files. I think I was misled by googling solutions to find these libraries, and the task was much simpler than I realized - great news all around. 

I bumped into a few other hurdles as I went through this, maybe they will be helpful to someone.
* gcc > 4.4 (at least, this is just my cluster default) is required, before boost installation and for compiling glimpse. I used gcc/9.2.0
* On my cluster, I had to load another module that includes some of the required libraries. This was included in a wrapper called GCCcore
* Additional libraries had to be explicitly included in the DYN_LIBS in each makefile as such:
```
DYN_LIBS=-lz -lpthread -lbz2 -llzma -lcurl -lcrypto
```
* If you edit the makefiles for cluster use, use `make cluster`. This isn't included in the toplevel makefile (maybe it could!), so has to be done on each software. 

I think there is also a typo on the [install page](https://odelaneau.github.io/GLIMPSE/installation.html) 

```
BOOST_LIB_PO (line 23): path to the static BOOST program_options library (file libboost_iostreams.a)
```
should be **libboost_program_options.a**
```
BOOST_LIB_PO (line 23): path to the static BOOST program_options library (file libboost_program_options.a)
```

The test files ran fine so I am looking forward to playing around with my data now. Thanks for your help! I learned something useful about gcc compilation here (I think). 

Erik
