### ISSUE TITLE
Parameters to speed up `GLIMPSE_phase`

### ISSUE THREAD

**Issue by nh13** [odelaneau/GLIMPSE#81]
We are looking at low hanging fruit to speed up the `GLIMPSE_phase` step without affecting theanalytical-performance of the step.

Besides parallelizing across genome chunks and samples, which we're already doing, are there settings for `GLIMPSE_phase` to maximize speed?  For example, some of the model parameters?

Also, if we are imputing on a WGS sample, but only at specific `--impute-reference-only-variants` markers, is there a performance penalty?  I could see the implementation use the VCF/BCF index to query the input WGS samples for each reference-marker, versus just streaming and filtering.  If it's just streaming the input sample already, then I suppose we could prune/filter the input VCF/BCF for the WGS sample to reduce the input size.

Does the input/output file format type matter?  For example, we're using `.vcf.gz` throughout, versus `.bcf` for some of the tutorial examples.

If we omit/include the genetic map, does that affect run time?

Any other considerations?

**Comment by srubinacci** [comment]
Hi,
Parallelizing across chunks is indeed required, however, as we show in our paper, GLIMPSE is actually faster with few hundred/thousands target samples at a time, instead of just few samples. This is because GLIMPSE has some constant operations to do on the reference panel, and it would gain some benefit from doing this only once for many samples.

Regarding the model parameters, the default settings allow good imputation quality at a reasonable time. Changing the model parameters (e.g. the number of iterations), could decrease imputation accuracy. In general, I would avoid decreasing these parameters, unless hardly tested. For reference, we investigated the effect of few of these parameters in our paper.

The effect of  ` --impute-reference-only-variants` is meant to impute missing variants in your likelihood file, but present in the reference panel. In general this option is not recommended, as we recommend to compute likelihoods at every position of the reference panel instead, to use reads information. This option is only for very specific applications, but I would not reccommend the usage in the general case. In the case the reference and the target share the same set of variants, omitting the parameter should be faster.

I would always recommend the use of BCF files for large cohorts / reference panels.

The specification of the genetic map does not affect significantly runtime (it is totally negligible to read this file and perform interpolation), but the performance loss would be dramatic, if the map is not specified.

If you/your organization heavily uses GLIMPSE and this has to be optimized in your use case, feel free to drop and email to me and especially Olivier.

Best wishes,

Simone
