### ISSUE TITLE
How to use GLIMPSE_concordance

### ISSUE THREAD

**Issue by alesss78** [odelaneau/GLIMPSE#9]
Thank you for develoing GLIMPSE!

We successfully used GLIMPSE to impute the NA12878 downsampled BAM file.
 
We want to  assess the quality of the imputation using the GLIMPSE_concordance function , however  we didn't find any documentation for it.
So we would like to know the data format for the required input files (True, Imputed, Frequencies, Regions).
Is Region imput necessary?
Additionally can you write an example of usage of the GLIMPSE_concordance function?
 
Can you please add some documentation about it?
Thank you

**Comment by SimoneRubinacci** [comment]
Hi,

Yes, it is indeed true that we haven't documented the GLIMPSE_concordance tool yet. For this reason I've just completely changed the tutorial (using different datasets) in order to include a validation dataset and to test the imputation accuracy of the sample NA12878.
You might need to pull the newest version of GLIMPSE and re-run the imputation, since the dataset changed - e.g. they are now in build38 - (sorry about it, hopefully will take just few minutes!). But then you will find an additional step where we use the GLIMPSE_concordance tool to assess the imputation accuracy. It's still not fully documented, but I hope that for the moment this "learn by example" is enough. 

Have a look at the new version of the tutorial:
https://odelaneau.github.io/GLIMPSE/tutorial.html#run_concordance

Let me know if you have any problems. Hope that answers to your question, at least for now.
Best wishes,
Simone

**Comment by alesss78** [comment]
Dear Simone,

Thank you very much for your prompt reply.
The documentation you added is very helpful.
The only thing I would ask is where can I find the "concordance.lst" file you mention in
section "8.1. Running GLIMPSE_concordance"?
Additionally, is it possible to run GLIMPSE_concordance with multiple files? I have 22 files (one for each chromosome) for each validation dataset, imputed genomes, and frequency files.
How to specify these files in a "concordance.lst" file?

Thank you again for your support!
Best

Alessandro

**Comment by SimoneRubinacci** [comment]
Hi Alessandro,

The concordance.lst is in the test folder (of the latest version of GLIMPSE): https://github.com/odelaneau/GLIMPSE/blob/master/test/concordance.lst
It is indeed possible to run the concordance tool for more than a single region. Just edit the concordance.lst file adding a line for each region (e.g. chromosome) of interest. The tool will automatically compute the concordance for all the regions considered and produce a single output.

Hope that will help.

Best wishes,

Simone
